### ISSUE TITLE
Changelogs with no releases should appear as just 'unreleased'

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/releases#36]
Friend of the project @sivy tried to use it for a wholly-unreleased changelog (i.e. no `:release:` directives whatsoever) and ran into what is probably just an assumption-related bug. See https://gist.github.com/sivy/2cf88b595722ffcb7163 for details. Offhand we should be able to cope with this (the parsing step should end with just the 'unreleased' release object holding all issues, and render as such).

**Comment by bitprophet** [comment]
Getting a different error when I try writing a test case proving this; looked closer and realized the issue here may be related to the bullet list inside Steve's sample RST - that would cause the "it's a unicode, I can't pop from it" error.

However, we definitely should be supporting that at this point (and as shown, having a release object somehow makes things work) so it may be a combination of factors. Hopefully fixing my vanilla test case will make this clearer.

**Comment by AndreLouisCaron** [comment]
I think I just hit this same issue.  I'm working on a v0.1 for my package and trying to track the set of features that will make it into the first release.

With releases v1.2.0, I get this exception:
```
Exception occurred:
  File "...\.tox\docs\lib\site-packages\releases\__init__.py", line 428, in handle_first_release_line
    manager.add_family(obj.family)
AttributeError: 'Issue' object has no attribute 'family'
```


  Looks to me like the problem is here:

```
def handle_first_release_line(entries, manager):
    """
    Set up initial line-manager entry for first encountered release line.

    To be called at start of overall process; afterwards, subsequent major
    lines are generated by `handle_upcoming_major_release`.
    """
    # It's remotely possible the changelog is totally empty...
    if not entries:
        return
    for obj in entries:
        if isinstance(obj, Release):
            break
    # Here, obj must be the 1st release item. Set it up.
    manager.add_family(obj.family)
```

If it loops through the entire list without hitting a `Release` object, `obj` will point to the last item in `entries`, which is a feature (issue) in my case.

**Comment by bitprophet** [comment]
Yea I don't think this ever got solved, nor was I cognizant of it when I was reorganizing the internals recently (re: multiple major 'families' of releases, i.e. it's now possible to display 'unreleased 0.x things' alongside 'unreleased 1.x things' etc). Hopefully not hard to fix though, especially now, after aforementioned reorganization. Would accept a patch, otherwise I'll try to poke it next time I revisit this project.

**Comment by bitprophet** [comment]
Poking this now. It's possible to neuter the couple of spots that assume >0 release objects exist in the changelog stream, and avoid the obvious exceptions.

However, we still end up in a bad place because even unreleased items (as of 1.2) need to be attached to some major release "family", i.e. "unreleased fixes for 0.x", "unreleased features for 1.x" etc.

I think this just means I need to further update the "find the first major release family" method so it adds an 0.x bucket even if it never really found any releases. Trying that now.

**Comment by bitprophet** [comment]
That sort-of works, but with the minor caveat that the bucketing can't tell bugfixes and features apart (there's nowhere for the bugfixes to "go") - see the last line item, *Bugs listed before the first release are treated as though they have the ‘major’ keyword*, under http://releases.readthedocs.io/en/latest/concepts.html#release-organization.

So one's changelog in this situation will have a single "Unreleased 0.x features" 'release' header, even if it's got stuff marked as "bugs" in it. Presumably not a huge issue for people, and potentially fixable if it is.

**Comment by AndreLouisCaron** [comment]
Thanks for fixing this!  Will be testing the next release :-)

**Comment by AndreLouisCaron** [comment]
Just tried this today on a new library, works like a charm, thanks!
